# Generated by Django 4.0.5 on 2022-06-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_pages', models.IntegerField()),
                ('book_price', models.IntegerField()),
                ('book_rating', models.FloatField()),
            ],
        ),
    ]
